spring:
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
    #需要实时更新的目录
      #additional-paths: resourse/**,static/**,templates/**
      exclude: templates/**

  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    initialization-mode: always
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 3
    max-active: 8
    min-idle: 2
    max-wait: -1
    min-evictable-idle-time-millis: 30000
    time-between-eviction-runs-millis: 0
    validation-query: select 1
    validation-query-timeout: -1
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true


#mybatis
mybatis-plus:
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.skyman.entity
  typeEnumsPackage:
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
  configuration:
    #驼峰方式
    map-underscore-to-camel-case: false
    cache-enabled: false
    call-setters-on-nulls: true
  mapper-locations: classpath:/mapper/*Mapper.xml
